from pathlib import Path
from bs4 import BeautifulSoup
from typing import Dict, Any, List


def inspect_html_for_selectors(html_path: str) -> List[str]:
    """
    Returns a list of human-readable element selectors found in the HTML:
    - id
    - name
    - class (first item)
    - text snippet

    This helps the autogenerated script give the user hints.
    """
    html = Path(html_path).read_text(encoding="utf-8")
    soup = BeautifulSoup(html, "html.parser")
    lines = []

    for el in soup.find_all(True):
        el_id = el.get("id")
        el_name = el.get("name")
        el_class = el.get("class")
        text = el.get_text(strip=True)[:40]

        if el_id or el_name or el_class:
            lines.append(
                f"<{el.name} id='{el_id}' name='{el_name}' class='{(el_class or [''])[0]}' text='{text}'>"
            )

    return lines


def generate_selenium_script(testcase: Dict[str, Any], html_path: str) -> str:
    """
    Produces a Selenium test skeleton.
    """

    tc_id = testcase.get("Test_ID", "TC-XXX")
    scenario = testcase.get("Test_Scenario", "")
    steps = testcase.get("Steps", [])

    # Format steps as commented lines in the script
    step_comments = "\n    # ".join(steps) if steps else "No detailed steps provided"

    # Inspect UI for selectors
    discovered = inspect_html_for_selectors(html_path)
    discovered_comment = "\n# ".join(discovered) if discovered else "No elements with id/name/class found."

    html_absolute = Path(html_path).resolve()

    script = f'''"""
Autogenerated Selenium script for {tc_id}
Scenario: {scenario}

Discovered selectors:
# {discovered_comment}
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time


def run_test():
    # Launch browser
    driver = webdriver.Chrome(ChromeDriverManager().install())

    try:
        # Load your UI file
        driver.get("file://{html_absolute}")
        time.sleep(1)

        # --------------------------------------------------
        # Test Steps From Test Case
        # --------------------------------------------------
        # {step_comments}

        # --------------------------------------------------
        # ACTION AREA — YOU NEED TO FILL THIS
        # --------------------------------------------------
        # Example actions (replace with real ones):
        # element = driver.find_element(By.ID, "<id_here>")
        # element.click()
        # element.send_keys("some text")
        # time.sleep(1)
        # result = driver.find_element(By.ID, "<some_result_id>").text
        # print("Result:", result)

        # Keep browser open so user can inspect
        input("Press ENTER to close browser...")

    finally:
        driver.quit()


if __name__ == "__main__":
    run_test()
'''

    return script